# Generated by Django 4.1.3 on 2022-11-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myapp',
            fields=[
                ('fname', models.AutoField(primary_key=True, serialize=False)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('num', models.CharField(max_length=100)),
                ('rtype', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
